name: flutter_trianglify
description: Flutter library to generate beautiful triangle art views for android and ios.
version: 0.0.2
homepage: https://github.com/JonathanMonga/flutter_trianglify
authors:
  - Jonathan Monga <jmonga98@gmail.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter